// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICombatSystem {
  function mud_CombatSystem_engage(bytes32 defender) external;

  function mud_CombatSystem_heal() external;
}
