// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { PositionTableData } from "./../systems/MoveSystem.sol";

interface IMoveSystem {
  function mud_move_move(int32 x, int32 y, int32 z) external returns (PositionTableData memory);
}
