// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPlayerSystem {
  function mud_PlayerSystem_spawn(uint32 id, int32 x, int32 y) external;
}
