// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IUploadSystem {
  function upload(
    int32[] memory xs,
    int32[] memory ys,
    int32[] memory zs,
    int32[] memory ws,
    int32[] memory hs,
    int32[] memory ds
  ) external;
}
