// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

enum ItemTypes {
  Unknown,
  Gold,
  EmberCrown,
  BlazingHeart,
  MovementBanner,
  SwordBanner,
  StaminaBanner,
  Crystal,
  Metal,
  Fossil,
  Widget
}
