// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

import { console } from "forge-std/console.sol";
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { SchemaType } from "@latticexyz/store/src/Types.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

// -- User defined schema and tableId --
struct CounterSchema {
  bool value;
}

uint256 constant CounterTableId = uint256(keccak256("/counter"));
uint256 constant tableId = CounterTableId;

// -- Autogenerated library to interact with tables with this schema --
// TODO: autogenerate

library CounterTable {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema schema) {
    schema = SchemaLib.encode(SchemaType.UINT32);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(tableId, getSchema());
  }

  function registerSchema(IStore store) internal {
    store.registerSchema(tableId, getSchema());
  }

  /** Set the table's data */
  function set(bytes32 key, uint32 value) internal {
    bytes32[] memory keyTuple = new bytes32[](1);
    keyTuple[0] = key;
    StoreSwitch.setRecord(tableId, keyTuple, abi.encodePacked(value));
  }

  function set(
    IStore store,
    bytes32 key,
    uint32 value
  ) internal {
    bytes32[] memory keyTuple = new bytes32[](1);
    keyTuple[0] = key;
    store.setRecord(tableId, keyTuple, abi.encodePacked(value));
  }

  /** Get the table's data */
  function get(bytes32 key) internal view returns (uint32) {
    bytes32[] memory keyTuple = new bytes32[](1);
    keyTuple[0] = key;
    bytes memory blob = StoreSwitch.getRecord(tableId, keyTuple);
    return uint32(bytes4(blob));
  }

  function get(IStore store, bytes32 key) internal view returns (uint32) {
    bytes32[] memory keyTuple = new bytes32[](1);
    keyTuple[0] = key;
    bytes memory blob = store.getRecord(tableId, keyTuple);
    return uint32(bytes4(blob));
  }
}
